[package]
name = "bob"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
which = "6"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
